### ISSUE TITLE
Assert all `model_texture`s and `transfer_texture`s are the same size

### ISSUE THREAD

**Issue by RobertGemmaJr** [brown-ccv/react-volume-viewer#113]
`updateSpacing` relies on the image width and height of the texture. Currently just using index 0. We should make sure all of the images are the same size, validation can be done in `volume.js` after loading all of the textures.

**Comment by kmilo9999** [comment]
I dont think this validation is needed here. If someone tries to blend volumes of different sizes, then we just render the artifacts.
