### ISSUE TITLE
check texture sizes should be optional (on by default)

### ISSUE THREAD

**Issue by kmilo9999** [brown-ccv/react-volume-viewer#134]
Blending two datasets of different number of slices throws an error due to texture sizes restrictions.
This should be optional in the library  in case we find this cases.  related to  #113

**Comment by RobertGemmaJr** [comment]
I'm not sure what you want me to implement. Right now they always have to be the same size. We would have to calculate the start and end position for each individual model again in order for this to work, which is fine if that's what you're looking for

**Comment by kmilo9999** [comment]
It should be possible to blend multiple datasets with different sizes. Right now, it throws an error when the volumes have a different width and height. Could you remove this check and/or make it optional?
