### ISSUE TITLE
Add storybooks to the library

### ISSUE THREAD

**Issue by RobertGemmaJr** [brown-ccv/react-volume-viewer#19]
I feel like storybooks would be an easier way to demo the project than this little example project we have going?

I'm not sure how we would be able to pass in the model and color map images though

**Comment by mcmcgrath13** [comment]
Yeah, I'm not sure how much we'd be able to meaningfully take advantage of storybook given the types of props we have.  The firebase deploy of the example would probably be faster to get up and running.  But I don't have a strong opinion here, I just want a way to preview PR's.

**Comment by RobertGemmaJr** [comment]
Using firebase for PR review, no need for storybooks
