### ISSUE TITLE
Load multiple models

### ISSUE THREAD

**Issue by kmilo9999** [brown-ccv/react-volume-viewer#49]
Right now the volume viewer only loads one model.  In the bay datasets we are only replacing the data texture of the main unit cube poised at the center of the scene.
We can add support to load more than one unit cube in scene and assign them their own data texture. This will help the case of showcasing multiple volumes in the same scene using VR.

**Comment by RobertGemmaJr** [comment]
Divide the scene into different viewports

**Comment by mirestrepo** [comment]
The links in [this comment](https://github.com/aframevr/aframe/issues/916#issuecomment-442907336) are relevant/interesting

**Comment by kmilo9999** [comment]
I think dividing the scene in different viewport should have its own issue. Loading multiple models is a different one.

**Comment by kmilo9999** [comment]
Load array of models as prop of the volume viewer tag.
Array of color maps.

**Comment by RobertGemmaJr** [comment]
Moved to issue #57
