### ISSUE TITLE
Ability to take multiple models, colorMaps, and transferFunctions

### ISSUE THREAD

**Issue by RobertGemmaJr** [brown-ccv/react-volume-viewer#57]
Microscopy dataset will overlay multiple `<a-entity>` models on top of each other, each with their own `colorMap` and `transferFunction`

The menu will need some sort of drop down to select each `model` individually and change it's `colorMap` and `transferFunction` from there

**Comment by RobertGemmaJr** [comment]
@mcmcgrath13 @kmilo9999 Should we force the user to pass in an array of models and transferFunctions? Or use internal checks to see if they only passed one in?

- `model` -> `models`
- `transferFunction` -> `transferFunctions`

**Comment by mcmcgrath13** [comment]
hmmmmmmmmmmm

**Comment by mcmcgrath13** [comment]
I can never remember whether ctrl-enter is new line or submit... 🤦 

I'm leaning models and force it to be an array.  It makes for more consistent types/documentation.  *But*, I also imagine that's the less common use case, so maybe we shouldn't make it the default.  What's your impression on what will be used more frequently?
